excluded: # paths to ignore during linting
  - iosApp/SupportingFiles/R.generated.swift
  - iosApp/SupportingFiles/terms_and_conditions.txt
  - iosApp/SupportingFiles/Info
  - iosApp/SupportingFiles/Assets
  - iosApp/SupportingFiles/Font/
  - iosApp/SupportingFiles/Launch Screen.storyboard
  - iosApp/SupportingFiles/Localizable
  - rswift
  
included: # paths to include during linting
  - iosApp/SupportingFiles/AppTheme.swift
  - iosApp/SupportingFiles/Constants.swift

disabled_rules: # rule identifiers turned on by default to exclude from running
  - multiple_closures_with_trailing_closure
  - identifier_name
  - trailing_whitespace

force_cast: warning # implicitly
force_try:
  severity: warning # explicitly

file_length:
  warning: 400
  error: 700
  
line_length:
  warning: 130
  error: 200
  ignores_comments: true
  ignores_urls: true

type_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
    
identifier_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
    
warning_threshold: 20
