name: Android lint

on: [pull_request]

jobs:
  android-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 21
          cache: gradle
      - name: Create local.properties
        run: | 
          echo "sdk.dir=$(pwd)/android-sdk" >> local.properties
          echo "crm.server = 0.0.0.0" >> local.properties
          echo "crm.port = 0" >> local.properties
          echo "crm.login = no_login" >> local.properties
          echo "crm.password.hash = abcd" >> local.properties
          echo "crm.test.refresh.token = abcd" >> local.properties
          echo "crm.test.access.token = abcd" >> local.properties
          echo "supabase.url = abcd" >> local.properties
          echo "supabase.public = abcd" >> local.properties
          echo "supabase.secret = abcd" >> local.properties
      - name: Run Android Lint
        run: ./gradlew lint
      - name: Upload lint results
        uses: actions/upload-artifact@v3
        with:
          name: lint-results
          ignore-warnings: true
          report-path: build/reports/.xml
