name: CI

on: [pull_request]

jobs:
  android-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 21
          cache: gradle
      - name: Create local.properties
        run: | 
          echo "sdk.dir=$(pwd)/android-sdk" >> local.properties
      - name: Run Android Lint
        run: |
          ./gradlew lint -Pandroid.lintOptions.check "!' + file('/home/runner/work/vodimobile-kmp-app/vodimobile-kmp-app/shared/build.gradle.kts')"
      - name: Upload lint results
        uses: actions/upload-artifact@v3
        with:
          name: lint-results
          ignore-warnings: true
          report-path: build/reports/.xml
