name: android unit test
on:
  push:
    paths:
      - .github/workflows/android-lint.yml
      - '*/src/**'
      - gradle/**
      - '**.gradle'
      - gradle.properties
      - gradlew*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Create local.properties
        run: |
          echo "sdk.dir=$(pwd)/android-sdk" >> local.properties
          echo "${{ secrets.LOCAL_PROPERTIES }}" >> local.properties
      - name: Create file
        run: cat ./androidApp/google-services.json | base64
      - name: Put data google-services.json
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" >> ./androidApp/google-services.json

      - name: Unit Test
        run: ./gradlew testDebugUnitTest

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless