name: shared unit test
on:
  pull_request:
    paths:
      - 'shared/src/commonMain/kotlin/com/vodimobile/domain/storage/supabase/**'
      - 'shared/src/commonMain/kotlin/com/vodimobile/domain/storage/crm/**'
      - 'shared/src/commonMain/kotlin/com/vodimobile/domain/repository/crm/**'
      - 'shared/src/commonMain/kotlin/com/vodimobile/domain/repository/supabase/**'
      - 'shared/src/commonMain/kotlin/com/vodimobile/domain/use_case/supabase/**'
      - 'shared/src/commonMain/kotlin/com/vodimobile/domain/use_case/crm/**'
      - 'shared/src/commonMain/kotlin/com/vodimobile/data/crm/**'
      - 'shared/src/commonMain/kotlin/com/vodimobile/data/supabase/**'
      - 'shared/src/commonMain/kotlin/com/vodimobile/utils/date_formats/**'
      - 'shared/src/commonTest/kotlin/com/vodimobile/**'
  push:
    paths:
      - 'shared/src/commonMain/kotlin/com/vodimobile/domain/storage/supabase/**'
      - 'shared/src/commonMain/kotlin/com/vodimobile/domain/storage/crm/**'
      - 'shared/src/commonMain/kotlin/com/vodimobile/domain/repository/crm/**'
      - 'shared/src/commonMain/kotlin/com/vodimobile/domain/repository/supabase/**'
      - 'shared/src/commonMain/kotlin/com/vodimobile/domain/use_case/supabase/**'
      - 'shared/src/commonMain/kotlin/com/vodimobile/domain/use_case/crm/**'
      - 'shared/src/commonMain/kotlin/com/vodimobile/data/crm/**'
      - 'shared/src/commonMain/kotlin/com/vodimobile/data/supabase/**'
      - 'shared/src/commonMain/kotlin/com/vodimobile/utils/date_formats/**'
      - 'shared/src/commonTest/kotlin/com/vodimobile/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 21
          cache: gradle
      - name: Create local.properties
        run: |
          echo "sdk.dir=$(pwd)/android-sdk" >> local.properties
          echo "${{ secrets.LOCAL_PROPERTIES }}" >> local.properties

      - name: Unit Test
        run: ./gradlew shared:testDebugUnitTest